binary_sensor:
  - platform: gpio
    internal: true
    pin: GPIO5
    name: "Rotary switch"
    on_click:
    - min_length: 0ms
      max_length: 350ms
      then:
        - script.execute: handle_short_button_press
    - min_length: 350ms
      max_length: 100000ms
      then:
        - script.execute: handle_long_button_press

script:
  - id: handle_short_button_press
    then:
      - sensor.rotary_encoder.set_value:
          id: rotary
          value: !lambda |-
            if (id(rotary).state > 0) {
              return 0;
            } else {
              return $default_brightness / (255 / $ring_leds);
            }

  - id: handle_long_button_press
    then:
      if:
        condition:
          api.connected:
        then:
          - script.execute: set_automatic
          - lambda: "id(encoder_sync_value) = id(auto_brightness).state;"
          - script.execute: synchronize_encoder

          # Force sending an update
          - delay: $dimming_interval s
          - script.execute: send_lights
          - script.execute: send_automations