esphome:
  name: $device_name
  platform: ESP8266
  board: esp12e
  on_boot:
    priority: -100
    then:
      - script.execute: init_dimmer    

# Credentials set in the secrets.yaml
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password


# Credentials set in the secrets.yaml
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: $device_name
    password: !secret ap_password

captive_portal:
logger:
api:
ota:

globals:
  - id: is_automatic
    type: bool
    restore_value: yes
    initial_value: "false"

status_led:
  pin:
    number: GPIO02
    inverted: false # Normally status LED is off, inverting it gives more feedback during debugging

# I need to improve this implementation, for now it's disabled
# binary_sensor:
#   - platform: gpio
#     internal: true
#     pin: 
#       number: GPIO1
#       mode: INPUT_PULLUP
#       inverted: true
#     name: "Charging"
#     on_press:
#       then:
#         - script.execute: set_charging

script:
  - id: init_dimmer
    then:
      - script.execute: set_ring_on 
      - delay: 10s
      - script.execute: set_automatic

  - id: set_automatic
    then:
      - lambda: "id(is_automatic) = true;"
      - lambda: "id(color_active)[0] = id(color_automatic)[0];"
      - lambda: "id(color_active)[1] = id(color_automatic)[1];"
      - lambda: "id(color_active)[2] = id(color_automatic)[2];"
  - id: set_manual
    then:
      - lambda: "id(is_automatic) = false;"
      - lambda: "id(color_active)[0] = id(color_manual)[0];"
      - lambda: "id(color_active)[1] = id(color_manual)[1];"
      - lambda: "id(color_active)[2] = id(color_manual)[2];"