sensor:
  - platform: homeassistant
    name: "Auto Color Temp"
    id: auto_color_temp
    entity_id: $auto_color_temp_id
    internal: true
  - platform: homeassistant
    name: "Auto brightness"
    id: auto_brightness
    entity_id: $auto_brightness_id
    internal: true
    on_value:
      - script.execute: received_auto_brightness_update

binary_sensor:
  - platform: homeassistant
    name: "Automation group"
    id: automation_group
    entity_id: $automation_group
    internal: true
    on_state:
     - script.execute: received_automation_group_update

mqtt:
  on_json_message:
    topic: $mqtt_light_topic
    then:
      - lambda: |-
          if(x.containsKey("brightness") && x.containsKey("state")) {
            if(strcmp(x["state"], "ON") == 0) {
              id(manual_brightness) = x["brightness"];
            } else {
              id(manual_brightness) = 0;
            }
          }
      - script.execute: received_manual_brightness_update

script:
  - id: send_automations
    mode: restart
    then:
      # Together with the mode: restart, this delay debounces the script
      - delay: 3s
      - if:
          condition:
            lambda: 'return id(is_automatic);'
          then:
            - homeassistant.service:
                service: homeassistant.turn_on
                data_template:
                  entity_id: "$automation_group"
          else:
            - homeassistant.service:
                service: homeassistant.turn_off
                data_template:
                  entity_id: "$automation_group"

  - id: send_lights
    then:
      - if:
          condition:
            api.connected:
          then:
            - mqtt.publish_json:
                topic: $mqtt_light_topic/set
                payload: |-
                  root["brightness"] = id(rotary).state;
                  root["color_temp"] = id(auto_color_temp).state;
                  root["transition"] = $dimming_interval;

  - id: received_automation_group_update
    then:
      - if:
          condition:
            lambda: 'return id(automation_group).state == true;'
          then:
            - script.execute: set_automatic
            - script.execute: received_auto_brightness_update
          else:
            - script.execute: set_manual
            - script.execute: received_manual_brightness_update

  - id: received_auto_brightness_update
    then:
      if:
        condition:
          lambda: 'return id(is_automatic);'
        then:
          - lambda: "id(synchronize_encoder) = true;"

          # Hack, handles case where auto brightness is identical to current brightness
          - script.execute: handle_short_button_press
          
          - sensor.rotary_encoder.set_value:
              id: rotary
              value: !lambda return id(auto_brightness).state / (255 / $ring_leds);
          - delay: $dimming_interval s # Hack, because of the encoder debounce we need to wait with setting this flag false
          - lambda: "id(synchronize_encoder) = false;"

  - id: received_manual_brightness_update
    mode: restart
    then:
    - if:
        condition:
          lambda: 'return !id(is_automatic) && !id(self_inflicted);'
        then:
          - lambda: "id(synchronize_encoder) = true;"
          - sensor.rotary_encoder.set_value:
              id: rotary
              value: !lambda return id(manual_brightness) / (255 / $ring_leds);
          - delay: $dimming_interval s # Hack, because of the encoder debounce we need to wait with setting this flag false
          - lambda: "id(synchronize_encoder) = false;"
    - lambda: 'id(self_inflicted) = false;'



